export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT_BY_CATERGORY = "GET_PRODUCT_BY_CATERGORY";
export const LOAD_SELECT_PRODUCT = "LOAD_SELECT_PRODUCT"
export const REMOVE_ALL_PRODUCT = "REMOVE_ALL_PRODUCT"
export const LOAD_BY_CATEGORY = "LOAD_BY_CATEGORY"
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"

